import './globals.css';
// Supports weights 100-900
import '@fontsource-variable/inter';

import * as stylex from '@stylexjs/stylex';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body {...stylex.props(style.body)}>{children}</body>
    </html>
  );
}

const style = stylex.create({
  body: {
    minBlockSize: '100dvb',
    backgroundColor: 'white',
    color: 'black',
    WebkitFontSmoothing: 'antialiased',
    display: 'grid',
    placeItems: 'center',
  },
});
